const dataStructreTypes = [
  "Array",
  "String ",
  "Linked List",
  "Stack",
  "Queue",
  "Tree",
  "Binary Tree",
  "BST",
  "Graph",
  "Heap",
  "Trie",
  "HashMap",
  "Sliding Window",
  "Two Pointer",
  "Greedy",
  "Backtracking",
  "Recursion",
  "Dynamic Programming",
  "Binary Search",
  "Prefix Sum",
  "Bit Manipulation",
];

const languageNumber = {
  63: "JavaScript",
  71: "Python",
  54: "C++",
  62: "Java",
  50: "C",
  51: "C#",
  60: "Go",
  73: "Rust",
  74: "TypeScript",
  68: "PHP",
  72: "Ruby",
};

const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

const unionTerritories = [
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

const indianLoactions = [...indianStates, ...unionTerritories];

module.exports = { dataStructreTypes, languageNumber, indianLoactions };
